version: "3.8"

services:
  shard0:
    build: .
    container_name: shard0
    command: python shard.py 5001
    ports:
      - "5001:5001"
  
  shard1:
    build: .
    container_name: shard1
    command: python shard.py 5002
    ports:
      - "5002:5002"

  shard2:
    build: .
    container_name: shard2
    command: python shard.py 5003
    ports:
      - "5003:5003"
  
  router:
    build: .
    container_name: router
    command: python router.py
    ports:
      - "5000:5000"
    depends_on:
      - shard0
      - shard1
      - shard2
